url: https://scu-ccs-coa.github.io
baseurl:

# Site settings
org: 四川大学网络空间安全学院计算机组成和体系结构课程组
title: 计算机组成和体系结构课程
logo: img/logo.png
email: kaigao◎scu.edu.cn
description: "四川大学网络空间安全学院计算机组成和体系结构课程网站"

# Build settings
markdown: kramdown
permalink: pretty
